CREATE TABLE `product_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT primary key,
  `product_name` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `product_englishName` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `product_no` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `product_oem` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `product_desc` varchar(2000) COLLATE utf8_bin DEFAULT NULL,
  `image_path` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `tech_name` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `spec_name` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `parent_supplier` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `creat_time` datetime DEFAULT NULL,
  `techId` bigint(20) DEFAULT NULL,
  `userId` bigint(20) DEFAULT NULL,
  `typeId` bigint(20) DEFAULT NULL,
  `brandId` bigint(20) DEFAULT NULL,
  `artNo` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `weight` varchar(200) COLLATE utf8_bin DEFAULT NULL,
  `del_flage` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `releas` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_43yup1uhjyc4qc99wvx064m4g` (`techId`),
  KEY `FK_7c4b811qg7l7mwxu06p8ndine` (`userId`),
  KEY `FK_cswjh2qa79wuoain6lpo8hklu` (`typeId`),
  KEY `FK_i9i5kos5cp7cs2x01sn91x0bk` (`brandId`),
  CONSTRAINT `FK_43yup1uhjyc4qc99wvx064m4g` FOREIGN KEY (`techId`) REFERENCES `product_tech` (`id`),
  CONSTRAINT `FK_7c4b811qg7l7mwxu06p8ndine` FOREIGN KEY (`userId`) REFERENCES `user_info` (`id`),
  CONSTRAINT `FK_cswjh2qa79wuoain6lpo8hklu` FOREIGN KEY (`typeId`) REFERENCES `product_type` (`id`),
  CONSTRAINT `FK_i9i5kos5cp7cs2x01sn91x0bk` FOREIGN KEY (`brandId`) REFERENCES `product_brand` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
